### ISSUE TITLE
Error 409: Conflict - Apology Required

### ISSUE THREAD

**Issue by csuwildcat** [mattbasta/mattbasta.github.com#2]
Hey Matt,

I wanted to file an issue because I always regarded you as a friend, and if there is an issue between us, I want to see that it gets RESOLVED: FIXED. Today, on the day you were reinstated the freedom to choose your own relationship ("reinstate" because it is a natural right you should never have been denied), I am happy for you. I am also sad, because it looks like I made you sad.

When I said on Twitter that I support ending government dictation of relationships, and hope polygamous families will also have their natural right to relationship choice restored, I was being sincere. I had no idea that you would see advocacy for freedom of other relationship types as a slight - that was certainly not my intent. As a straight, white male I have never experienced the struggles of people in either gay or polygamous relationships. Perhaps that inexperience is why I wasn't aware of how you would feel about my statement.

I must make one thing clear: I support relationship freedom for every person of every sex, orientation, and family type. I can't apologize for that, it's rooted in the deeply held belief that government has no right to intrude on personal decisions and individual choice - especially in something as personal as our relationships.

Matt, you are a funny, smart, gifted developer. I would hate to lose such a great guy as a friend. Please accept my apology, I am truly sorry if I offended you.

**Comment by mattbasta** [comment]
Calm down buchner, it's fine. Just don't be an ass.
